services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: post
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

